# Author: Elías Gabriel Ferrer Jorge

"""
Step 0: Directory Initialization for Bias Modeling Pipeline

This module is responsible for preparing the directory structure required for the bias calibration pipeline.
It ensures that all outputs from later stages (master bias creation, synthetic mask generation, and model fitting)
are saved consistently and independently.

This step should always be executed before any data processing begins.
"""

import os
from tqdm import tqdm

def create_directories(output_base_dir: str) -> dict:
    """
    Create the required directory hierarchy under the specified output base path.

    Output structure:
    ------------------
      bias_grouped_by_temp/   : Stores real (observed) master bias frames, grouped by temperature.
      bias_masks_by_temp/     : Stores synthetic bias frames generated by the fitted model.
      bias_model/             : Stores model coefficients or polynomial maps (a_map, b_map, etc).

    Parameters:
    ------------
    output_base_dir : str
        Absolute or relative path to the base output directory.

    Returns:
    ---------
    dict[str, str]
        Dictionary with logical names mapping to full directory paths.
        Example: {'bias_data_dir': ..., 'bias_masks_dir': ..., 'model_dir': ...}
    """
    subdirs = {
        'bias_data_dir': os.path.join(output_base_dir, "bias_grouped_by_temp"),
        'bias_masks_dir': os.path.join(output_base_dir, "bias_masks_by_temp"),
        'model_dir': os.path.join(output_base_dir, "bias_model")
    }

    print("\n[Step 0] Creating output directory structure...")
    for key, path in tqdm(subdirs.items(), desc="Creating directories", ncols=80):
        os.makedirs(path, exist_ok=True)

    return subdirs
