# Author: Elías Gabriel Ferrer Jorge

"""
Step 0: Manage and create the output directories needed for subsequent steps in the bias pipeline.
This script ensures a consistent structure for saving intermediate and final results.
"""

import os
from tqdm import tqdm


def create_directories(output_base_dir: str) -> dict:
    """
    Creates the necessary subdirectories within the specified output base directory for bias modeling.

    The directory structure is as follows:
        - bias_grouped_by_temp: Stores master bias frames grouped by temperature.
        - bias_masks_by_temp: Stores synthetic bias frames generated by the model.
        - bias_model: Stores the fitted model maps (e.g., a_map, b_map, etc.).

    :param output_base_dir: The base directory where all pipeline outputs will be stored.
    :type output_base_dir: str
    :return: A dictionary containing paths to the created subdirectories.
    :rtype: dict[str, str]
    """
    # Define subdirectories
    subdirs = {
        'bias_data_dir': os.path.join(output_base_dir, "bias_grouped_by_temp"),
        'bias_masks_dir': os.path.join(output_base_dir, "bias_masks_by_temp"),
        'model_dir': os.path.join(output_base_dir, "bias_model")
    }

    print("\n[Step 0] Creating output directory structure...")
    for key, path in tqdm(subdirs.items(), desc="Creating directories", ncols=80):
        os.makedirs(path, exist_ok=True)

    return subdirs
